import type { Metadata } from "next";
import Link from "next/link";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/next"
import ThemeToggle from "./components/theme_toggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const title = "Olympiad Tracker — Competition calendar & parser";
const description = "Parse academic competition pages, extract dates & details, and add events to your calendar.";

export default function RootLayout({ children, }: Readonly<{children: React.ReactNode;}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          <title>{title}</title>
          <meta name="description" content={description} />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <script
            dangerouslySetInnerHTML={{
              __html: `(function(){try{var t=localStorage.getItem("theme");var d=t?t==="dark":window.matchMedia("(prefers-color-scheme: dark)").matches;document.documentElement.classList.toggle("dark",d);}catch(e){}})();`,
            }}
          />
          <link rel="icon" href="/favicon.ico" />
          {/* Open Graph */}
          <meta property="og:type" content="website" />
          <meta property="og:title" content={title} />
          <meta property="og:description" content={description} />
          <meta property="og:image" content={`https://trackolymp.tech/og-image.png`} />
          <meta property="og:url" content="https://trackolymp.tech" />
          <meta property="og:site_name" content="Olympiad Tracker"/>

          {/* Twitter */}
          <meta name="twitter:card" content="summary_large_image" />
          <meta name="twitter:title" content={title} />
          <meta name="twitter:description" content={description} />

        </head>
        <body className={`--font-geist-sans --font-geist-mono antialiased`}>
          <SpeedInsights/>
          <header className="sticky top-0 z-50 border-b border-white/10 bg-background/75 backdrop-blur-md">
            <div className="mx-auto flex max-w-7xl items-center justify-between gap-4 p-4">
            <Link className="text-lg font-semibold tracking-tight" href="/">Trackolymp.tech</Link>
            <div className="flex items-center gap-3">
              <ThemeToggle />
              <SignedOut>
                <SignInButton>
                  <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                    Sign In
                  </button>
                </SignInButton>
                <SignUpButton>
                  <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <Link href="/dashboard" className="rounded-full border border-[#6c47ff] px-4 py-2 text-sm font-medium text-[#6c47ff] transition hover:bg-[#f2edff]">
                  Dashboard
                </Link>
                <Link href="/profile" className="rounded-full border border-[#6c47ff] px-4 py-2 text-sm font-medium text-[#6c47ff] transition hover:bg-[#f2edff]">
                  Profile
                </Link>
                <UserButton />
              </SignedIn>
            </div>
            </div>
          </header>
          {children}
          <Analytics />
        </body>
      </html>
    </ClerkProvider>
  );
}
