import type { Metadata } from "next";
import Link from "next/link";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/next"
import ThemeToggle from "./components/theme_toggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const title = "Olympiad Tracker — Competition calendar & parser";
const description = "Parse academic competition pages, extract dates & details, and add events to your calendar.";

export default function RootLayout({ children, }: Readonly<{children: React.ReactNode;}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          <title>{title}</title>
          <meta name="description" content={description} />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <script
            dangerouslySetInnerHTML={{
              __html: `(function(){try{var t=localStorage.getItem("theme");var d=t?t==="dark":window.matchMedia("(prefers-color-scheme: dark)").matches;document.documentElement.classList.toggle("dark",d);}catch(e){}})();`,
            }}
          />
          <link rel="icon" href="/favicon.ico" />
          {/* Open Graph */}
          <meta property="og:type" content="website" />
          <meta property="og:title" content={title} />
          <meta property="og:description" content={description} />
          <meta property="og:image" content={`https://trackolymp.tech/og-image.png`} />
          <meta property="og:url" content="https://trackolymp.tech" />
          <meta property="og:site_name" content="Olympiad Tracker"/>

          {/* Twitter */}
          <meta name="twitter:card" content="summary_large_image" />
          <meta name="twitter:title" content={title} />
          <meta name="twitter:description" content={description} />

        </head>
        <body className={`--font-geist-sans --font-geist-mono antialiased bg-white`}>
          <SpeedInsights/>
          <header className="p-4 relative">
            <div className="flex flex-row-reverse text-2xl font-bold rounded text-center justify-center w-full bg-[#001f3f] text-white p-3">
              <Link className="text-2xl font-bold rounded text-center w-full bg-[#001f3f] text-white p-3" href="/">
                Trackolymp.tech
              </Link>
              <a href="https://www.producthunt.com/products/olympiad-tracker?embed=true&amp;utm_source=badge-featured&amp;utm_medium=badge&amp;utm_campaign=badge-olympiad-tracker" target="_blank" rel="noopener noreferrer"><img alt="Olympiad Tracker - Olympiad calendar helping you track competitions | Product Hunt" width="250" height="54" src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=1141101&amp;theme=neutral&amp;t=1781031084195" /></a>
            </div>
            <div className="absolute top-0.5 bottom-2 right-4 flex items-center gap-4 mr-4 h-full">
              <ThemeToggle />
              <SignedOut>
                <SignInButton>
                  <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                    Sign In
                  </button>
                </SignInButton>
                <SignUpButton>
                  <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <Link href="/dashboard" className="rounded-full border border-[#6c47ff] px-4 py-2 text-sm font-medium text-[#6c47ff] transition hover:bg-[#f2edff]">
                  Dashboard
                </Link>
                <Link href="/profile" className="rounded-full border border-[#6c47ff] px-4 py-2 text-sm font-medium text-[#6c47ff] transition hover:bg-[#f2edff]">
                  Profile
                </Link>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          {children}
          <Analytics />
        </body>
      </html>
    </ClerkProvider>
  );
}
